#!/bin/bash

start="now"
end="now"
format=""
help="
Usage: $0 [start [end]] [-m|-h|-d]|[-h]

    Calculates the difference between a start and end date, in seconds. Dates default to 'now'.
    Additional flag can be supplied to output difference in alternate units.
    
    --start: Start date
    --end: End date
    -m: Output difference in MINUTES
    -h: Output difference in HOURS
    -d: Output difference in DAYS
    --help: Display this help dialog and exit
    
    Example: Seconds elapsed between two given dates:
        datediff --start \"2010-04-04\" --end \"2011-04-04\"
    
    Example: Days elapsed since a given date:
        datediff --start \"2018-06-05\" -d"

for arg in "$@"; do
    if [ $arg == "--help" ]; then
        echo "$help"; exit 0
    fi
done

while [ $# -gt 0 ]; do
    case $1 in
    --start|--end)
        arg=${1:2}
        shift
        if [ $# -gt 0 ]; then
            eval "$arg=\"$1\""
        else
            printf "ERROR: '--$arg' supplied without value.\nRun with '--help' for help.\n"
            exit 1
        fi
        shift;;
        
    -m|-h|-d)
        format=${1:1}; shift;;
        
    *)
        echo "$help"; exit 1;;
    esac
done

if [ $start == "now" ] && [ $end == "now" ]; then
    echo 0; exit 0
fi

t1=$(date -d "$start" +%s)
t2=$(date -d "$end" +%s)
diff=$(( t2-t1 ))

case $format in
m)
    echo $(( diff/60 ));;
h)
    echo $(( diff/60/60 ));;
d)
    echo $(( diff/60/60/24 ));;
*)
    echo $diff;;
esac 